---
- name: Install apt-get repositories
  become: true
  apt_repository: repo='{{ item }}'
                  state=present
  with_items:
    - ppa:stefansundin/truecrypt
    - ppa:ansible/ansible
    - ppa:webupd8team/tor-browser
    - deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
    - deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
    - deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse
    - deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse
    - deb http://apt.syncthing.net/ syncthing release

- name: Add repository keys
  become: true
  apt_key: url='https://syncthing.net/release-key.txt'
           state=present

- name: Install Desktop
  become: true
  apt: name=ubuntu-desktop
       state=latest
       update_cache=yes

- name: Install Common Programs
  become: true
  apt: name='{{ item }}'
       state=latest
  with_items:
    - amarok
    - anacron
    - ansible
    - aptitude
    - asunder
    - autojump
    - baobab
    - brasero
    - calibre
    - clamav
    - clamav-daemon
    - clamav-freshclam
    - clamtk
    - chromium-browser
    - clementine
    - command-not-found
    - command-not-found-data
    - curl
    - firefox
    - flashplugin-installer
    - gedit
    - git
    - gimp
    - gnome-disk-utility
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - haskell-platform
    - keepassx
    - keepass2
    - keychain
    - lftp
    - libreoffice
    - libsmpeg0
    - lynx
    - mcomix
    - mplayer
    - network-manager
    - okular
    - openssh-server
    - p7zip-full
    - python2.7
    - python-setuptools
    - redshift-gtk
    - secure-delete
    - software-properties-common
    - software-properties-gtk
    - soundconverter
    - soundkonverter
    - ssh
    - syncthing
    - terminator
    - thunderbird
    - tor-browser
    - truecrypt
    - unattended-upgrades
    - unity-tweak-tool
    - unrar
    - unzip
    - vim
    - vlc
    - xdotool
    - wget
    - wine
    - xournal
    - zsh

- name: Upgrade Packages
  become: true
  apt: upgrade=safe
