---
- name: Install apt-get repositories
  become: true
  apt_repository: repo='{{ item }}'
                  state=present
  with_items:
    - deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
    - deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
    - deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse
    - deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse

- name: Install Common Programs
  become: true
  apt: name='{{ item }}'
       state=latest
  with_items:
    - amarok
    - anacron
    - ansible
    - aptitude
    - asunder
    - autoconf
    - autojump
    - baobab
    - bison
    - bleachbit
    - bluetooth
    - bluez
    - brasero
    - build-essential
    - ca-certificates
    - calibre
    - cdparanoia
    - clamav
    - clamav-daemon
    - clamav-freshclam
    - clamtk
    - chromium-browser
    - clementine
    - command-not-found
    - command-not-found-data
    - curl
    - diffutils
    - evince
    - ffmpeg
    - firefox
    - flac
    - flashplugin-installer
    - fonts-firacode
    - "g++"
    - gargoyle-free
    - gedit
    - git
    - gimp
    - gnome-disk-utility
    - gnome-keyring
    - gnome-settings-daemon
    - gnome-tweaks
    - gnupg
    - gparted
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gzip
    - haskell-platform
    - imagemagick
    - keepassx
    - keepass2
    - keychain
    - kdenlive
    - libgdbm5
    - libgdbm-dev
    - libffi-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - lftp
    - libreoffice
    - libsmpeg0
    - lynx
    - make
    - mplayer
    - network-manager
    - net-tools
    - octave
    - okular
    - openjdk-11-jdk
    - openssh-server
    - p7zip-full
    - playonlinux
    - python2.7
    - python-setuptools
    - qt5-default
    - qt5-qmake
    - rake
    - recordmydesktop
    - redshift-gtk
    - rsync
    - ruby
    - secure-delete
    - sgt-puzzles
    - software-properties-common
    - software-properties-gtk
    - soundconverter
    - sqlite3
    - ssh
    - ssh-askpass
    - sshpass
    - syncthing
    - terminator
    - thunderbird
    - torbrowser-launcher
    - tree
    - ubuntu-make
    - unattended-upgrades
    - unity-tweak-tool
    - unrar
    - unar
    - unzip
    - vagrant
    - vim
    - virtualbox
    - vlc
    - xdotool
    - wget
    - wine-stable
    - winetricks
    - xournal
    - zlib1g-dev
    - zsh

- name: Upgrade Packages
  become: true
  apt: upgrade=safe
