---
- name: Create Terminator Config Directory
  file: path=/home/{{ ansible_user_id }}/.config/terminator state=directory

- name: Configure Terminator
  copy: src=files/terminator.config
        dest=/home/{{ ansible_user_id }}/.config/terminator/config
