---
- name: Install Webupd Java PPA
  become: true
  apt_repository: repo=ppa:webupd8team/java
                  state=present
  register: java

- name: Accept Oracle 8 Terms
  become: true
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  when: java.changed

- name: Install Javas
  become: true
  apt: name={{ item }}
       state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
