---
- name: Creates Config Directory
  file: path=/home/{{ ansible_user_id }}/.config
        state=directory

- name: Copy Redshift configuration
  copy: src=files/redshift.conf
        dest=/home/{{ ansible_user_id }}/.config/redshift.conf
